In [1]:
#TASK ONE - THIS WORKS BUT I DO NOT KNOW HOW TO PUT A SPACE BETWEEN EACH NUMBER 

# 1.1 - open a data file and write a string with a new line per thing (?) 
# Not sure what the 10 is (play around later)

# FROM 14

my_file=open("task1_four_numbers.txt","w")

for i in range (10):
    my_file.write (str(i))
    my_file.write("\n")

my_file.close ()

In [2]:
#1.2 - I think that this is writing the numbers

my_file = open ("task1_four_numbers.txt","w")

my_file.write(str(7))
my_file.write(str(45))
my_file.write(str(83))
my_file.write(str(21))

my_file.close()


In [3]:
# 1.3 - read and print task_1_four_numbers

with open ("task1_four_numbers.txt", "r") as myfile:
    data = myfile.read()

myfile.close

print (data)   








7458321


In [4]:
#1.4  amend the file

my_file = open ("task1_four_numbers.txt", "a")

my_file.write ("    Wish I could put spaces between these numbers!!")

my_file.close ()

In [3]:
# 1.5- i think this is reading file from task_1_four_numbers

with open ("task1_four_numbers.txt", "r") as myfile:
    data = myfile.read()

myfile.close

print (data)   


    Wish I could put spaces between these numbers!


In [6]:
#
#TASK 2
# ASK A STUDENT THEIR PERCENTAGE MARK, COVERT IT TO A GRADE - USE A FUNCTION CALLED 'MARK_GRADE'print

percentage_score = int (input ("what is your percentage?"))

def mark_grade ():
    if percentage_score <=50:
        print ("You have got a grade 1 to 3")

    elif percentage_score >= 85:
        print("You have got a grade 9!")

    else: print ("You have got a grades 4 to 8")

mark_grade ()


You have got a grade 1 to 3


In [109]:
# EXTENSION # - works but does not allow to convert mark to grade before comparing 

#Ask the user for their target grade and print this with their mark
#• If their target grade > exam grade display a suitable message
#• If their target grade = exam grade display a suitable message
#• If their target grade < exam grade display a suitable message


percentage_score = int (input ("What percentage did you score?"))
target_grade    = int (input ("What is your target grade?"))

def target_vs_actual ():
    if percentage_score == target_grade:
        print ("Amazing - you got eactly what you expected!")

    elif percentage_score > target_grade:
        print("Wow - you exceeded your target grade")

    else: print ("You didn't reach your target range - try working harder next time!")

target_vs_actual ()

Wow - you exceeded your target grade


In [135]:
#EXTENSION - THIS ALLOWS YOU TO CONVERT TO A GRADE, BUT I CANNOT GET IT TO WORK!!
# IT IS VERY CLOSE...!
# IF I GET RID OF THE CODING UNDER 'ELSE', IT RUNS BUT STILL THE LOGIC DOES NOT WORK PROPERLY 

percentage_score = int (input ("What percentage did you score?"))

def mark_grade():

    if percentage_score <50:
        print ("You have got a grade C")
        grade_achieved = 3
        grade_achieved = int(grade_achieved)
        print (grade_achieved)

    elif percentage_score > 85:
        print("You have got a grade A!")
        grade_achieved = 1
        grade_achieved = int(grade_achieved)
        print (grade_achieved)

    else: print ("You have got a grade B")
                grade_achieved = 2
            grade_achieved = int(grade_achieved)
            print (grade_achieved)




mark_grade ()




target_grade = input("What was your target grade? - if A, input '1', if B input '2' and if C, put '3'")
target_grade = int(target_grade)

if target_grade=grade_achieved:
   print ("Shame you didn't get the grade you wanted - better luck in your exams next time")

if target_grade < grade_achieved:
    print ("Well done - you exceeded your grade!")

else: print ("You got your expected grade")



#elif input_number1


   

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 21)

In [5]:
pip install numpy

You should consider upgrading via the 'C:\Users\cdwm1\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [10]:
# NUMPY TASK 1 - 
#
# Create a 1D array of numbers from 0 to 9

import numpy as np
even = np.arange (10)
print (even)





[0 1 2 3 4 5 6 7 8 9]


In [13]:
# NUMPY TASK 1
# AN ALTERNATIVE WAY

import numpy as np
array = np.array ([0,1,2,3,4,5,6,7,8,9])
print (array)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
# NUMPY TASK 2 - 3 X 3 ARRAY OF ALL BOOLEAN TRUE VALUES

bool_arr = np.ones((3,3), dtype=bool)
print(bool_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [48]:
# Same 9 True values but NOT in 3 x 3 grid
bool_arr = np.ones(9, dtype=bool)

print(bool_arr)



[ True  True  True  True  True  True  True  True  True]


In [56]:
# NUMPY TASK 3 
#  extract all odd numbers from array of 1-10

import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
print(array)

odds = [n for n in array if n%2]
print (odds)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 3, 5, 7, 9]


In [58]:
# NUMPY TASK 4 -
# replace all odd numbers in an array 
# of 1-10 with the value -1
# the % sign denotes the remainder when two numbers
# are divided, so when the remainder of the numbers
# in 'a' have a remainder of 1, these are 'odd values'
# and then it makes all odd values '-1'

import numpy as np 
 
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
odd_values = (a%2 == 1) 
a[odd_values] = -1 
print (a)
# array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10]) 

 


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [59]:
# NUMPY TASK 4 - SHORTER WAY
# 
import numpy as np 
 
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
a[a%2 == 1] = -1  
print (a)


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [64]:
# NUMPY TASK 5
# Convert a 1D array to a 2D array with 2 rows

# create 1D numpy array from a list
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')


print(arr)

arr_2d = np.reshape(arr, (2, 5))

print('2D Numpy array:')
print(arr_2d)




1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [78]:
# NUMPY TASK 6 
# Create two arrays a and b, stack these two 
# arrays vertically use the np.dot and 
# np.sum to calculate totals

import numpy as np
a = np.arange (3,19).reshape (4,4) 
b = np.arange (13,29).reshape (4,4
) 
c = np.dot(a, b)

sum = np.sum (c)

e = np.sum(c,axis = 0)



print (a)
print (b)
print(c)

print("Here is the total of each column:\n", e)
print ("And the total number when all the mulplied numbers are added together is:\n",sum)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]
[[ 362  380  398  416]
 [ 666  700  734  768]
 [ 970 1020 1070 1120]
 [1274 1340 1406 1472]]
Here is the total of each column:
 [3272 3440 3608 3776]
And the total number when all the mulplied numbers are added together is:
 14096


In [ ]:
"""
Extension:
1. Create the following pattern without hardcoding. Use only NumPy functions.
2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b
3. Get all items between 3 and 7 from a and b and sum themtogethe

In [137]:
#ext 1. Create the following pattern without hardcoding. Use only NumPy functions.

import numpy as np

arr1 = np.array([1, 1, 1])

arr2 = np.array([2, 2, 2])

arr3 = np.array([3, 3, 3])

arr4 = np.array ([1,2, 3])

arr = np.concatenate((arr1, arr2, arr3, arr4, arr4, arr4))

print(arr)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [157]:
# 2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

list_1 = np.array([ 1,2,3,4,5])

list_2 = np.array([4,5,6,7,8,9])

new_list_2 = set (list_2) - set (list_1)

print (new_list_2)



{8, 9, 6, 7}


In [ ]:
# Get all items between 3 and 7 from a and b and sum them together
# NOT MANAGED TO WORK THIS OUT YET - WILL KEEP TRYING AND PUSH LATER 